# This is a basic workflow to help you get started with Actions

name: First Worklow

# Controls when the workflow will run
on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello, world!
      - name: print goodbye
        run: | 
          echo "Done bye"
 
